[project]
name = "stt-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Alex Severin", email = "severinalexeyv@gmail.com" }]
requires-python = "==3.11.11"
dependencies = [
    "boto3>=1.36.23",
    "common",
    "pika>=1.3.2",
    "psycopg-pool>=3.2.5",
    "psycopg[binary]>=3.2.5",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.0",
]

[tool.uv.sources]
common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["types-boto3[essential]>=1.37.0", "types-pika-ts>=1.3.0.20241203"]
