FROM python:3.12.9-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY . .
RUN apt-get -y update && apt-get -y install curl
RUN uv sync --frozen --no-cache --package=nlp-api

ENV CFG_PATH=./config.json
CMD ["/app/.venv/bin/fastapi", "run", "packages/nlp-api/src/nlp_api/app.py", "--port", "80"]
