FROM python:3.11-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY . .
RUN uv sync --frozen --no-cache --package=nlp-worker

ENV CFG_PATH=./packages/nlp-worker/config.json
CMD ["uv", "run", "--no-sync", "packages/nlp-worker/main.py"]
