FROM python:3.12.9-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY . .
RUN uv sync --frozen --no-cache --package=stt-worker

ENV CFG_PATH=./config.json
CMD ["uv", "run", "--no-sync", "packages/stt-worker/main.py"]
