[project]
name = "common"
version = "0.1.0"
description = "common utils"
readme = "README.md"
authors = [{ name = "Alex Severin", email = "severinalexeyv@gmail.com" }]
requires-python = ">=3.12.9"
dependencies = [
    "faster-whisper>=1.1.1",
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
